export const text1 = [
  "JAN",
  "FEB",
  "MAR",
  "APR",
  "MAY",
  "JUN",
  "JUL",
  "AUG",
  "SEP",
  "OCT",
  "NOV",
  "DEC",
];

export const text2 = [
  "Kurt Pan",
  "7k",
  "Kay Yu",
  "Shiyu",
  "Fang Ting",
  "Twone",
  "Maymay",
  "Yijing",
  "Big Song",
  "Lauran",
  "Wingo",
  "York",
  "Nicholas",
  "935",
  "flytoufu",
  "zhoumo",
  "cube",
  "Haotian",
  "larri",
  "Jocelyn",
  "17",
  "ada",
  "yifan",
  "Raven",
  "Alexis",
  "cejay",
  "Survivor",
  "Aaron",
  "zik",
];

export const text3 = [
  "Crypto Wars: Faked Deaths, Missing Billions and Industry Disruption",
  "The Blockchain and the new architecture of digital trust",
  "Cypherpunks: Freedom and the Future of the Internet",
  "The Sovereign Individual: Mastering the Transition to the Information Age",
  "Bitcoin: A Peer-to-Peer Electronic Cash System",
  "Blind Signatures for Untraceable Payments",
  "Computer Systems Established, Maintained, and Trusted by Mutually Suspicious Groups",
  "The Crypto Anarchist Manifesto",
  "Cyberspace, Crypto Anarchy, and Pushing Limits",
  "The Cyphernomicon",
  "Denationalisation of Money: The Argument Refined",
  "The Idea of Smart Contracts",
  "Money, Blockchains, and Social Scalability",
  "d/acc: one year later",
  "Make Ethereum Cypherpunk Again",
  "The Revenue-Evil Curve: a different way to think about prioritizing public goods funding",
  "DAOs are not corporations: where decentralization in autonomous organizations matters",
  "In Defense of Bitcoin Maximalism",
  "The roads not taken",
  "Decentralized Society: Finding Web3's Soul",
  "Radical Markets: Uprooting Capitalism and Democracy for a Just Society",
  "Liberal Radicalism: A Flexible Design for Philanthropic Matching Funds",
  "Flash Boys 2.0: Frontrunning, Transaction Reordering, and Consensus Instability",
  "The Bitcoin Lightning Network: Scalable Off-Chain Instant Payments",
  "The Theory of Money and Credit",
  "Trusted Third Parties are Security Holes",
  "Ethereum: A Next-Generation Smart Contract and Decentralized Application Platform",
];
